### ISSUE TITLE
Example should be renamed to include simpletest

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_FocalTouch#10]
Example `focaltouch_simple_paint.py` should be renamed to `focaltouch_paint_simpletest.py` to fit with CircuitPython library standards.

The lines including this file name in the `docs/examples.rst` file must also be updated to reflect the name change, e.g.:
```
.. literalinclude:: ../examples/current_file_name.py
    :caption: examples/current_file_name.py
    :linenos:
```
would be updated to:
```
.. literalinclude:: ../examples/current_file_name_changed.py
    :caption: examples/current_file_name_changed.py
    :linenos:
```

**Comment by dsudduth** [comment]
Hi @kattni and @sommersoft! I've created a PR to address the issue. Please let me know if any additional changes are needed. 😄
