### ISSUE TITLE
ValueError: incompatiple .mpy file with CircuitPython 9?

### ISSUE THREAD

**Issue by somenice** [adafruit/Adafruit_CircuitPython_FocalTouch#30]
Hey there, I know it's early days.
I'm using the latest CP9 release trying to get touch working with round touch 480x480 on Qualia S3
Using the latest 8.x library I get "ValueError: incompatiple .mpy file" 

Adafruit CircuitPython 9.0.0-alpha.1-77-g2c47221cac on 2023-10-21; Adafruit-Qualia-S3-RGB666 with ESP32S3

Is only CP8/Arduino supported so far?  
re. https://learn.adafruit.com/adafruit-qualia-esp32-s3-for-rgb666-displays/circuitpython-touch-display-usage
https://learn.adafruit.com/adafruit-qualia-esp32-s3-for-rgb666-displays/arduino-touch-display-usage
Thank you

**Comment by makermelissa** [comment]
You can use a .py file instead of the .mpy version for now.

**Comment by somenice** [comment]
Thank you @makermelissa
